create extension if not exists pgcrypto;

create table if not exists public.products (
  id uuid primary key default gen_random_uuid(),
  slug text not null unique,
  name text not null,
  price numeric(12, 2) not null default 0 check (price >= 0),
  sales_count integer not null default 0 check (sales_count >= 0),
  sale_price numeric(12, 2) check (sale_price is null or (sale_price >= 0 and sale_price < price)),
  images jsonb not null default '[]'::jsonb,
  variants jsonb not null default '[]'::jsonb,
  category text not null default 'Supplements',
  goal text not null default 'Everyday wellness',
  image_url text,
  stock integer not null default 0 check (stock >= 0),
  description text not null default '',
  ingredients text not null default '',
  how_to_use text not null default '',
  facts jsonb not null default '{}'::jsonb,
  faq jsonb not null default '[]'::jsonb,
  published boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.products add column if not exists sale_price numeric(12, 2);
alter table public.products add column if not exists sales_count integer not null default 0;
alter table public.products add column if not exists images jsonb not null default '[]'::jsonb;
alter table public.products add column if not exists variants jsonb not null default '[]'::jsonb;
alter table public.products drop constraint if exists products_sale_price_valid;
alter table public.products add constraint products_sale_price_valid
  check (sale_price is null or (sale_price >= 0 and sale_price < price));
alter table public.products drop constraint if exists products_images_array;
alter table public.products add constraint products_images_array
  check (jsonb_typeof(images) = 'array');
alter table public.products drop constraint if exists products_variants_array;
alter table public.products add constraint products_variants_array
  check (jsonb_typeof(variants) = 'array');

create table if not exists public.admin_users (
  user_id uuid primary key references auth.users(id) on delete cascade,
  created_at timestamptz not null default now()
);

create or replace function public.is_zoenaturals_admin()
returns boolean
language sql
stable
security definer
set search_path = ''
as $$
  select exists (
    select 1
    from public.admin_users
    where user_id = (select auth.uid())
  );
$$;

revoke all on function public.is_zoenaturals_admin() from public;
grant execute on function public.is_zoenaturals_admin() to anon, authenticated;

alter table public.products enable row level security;
alter table public.admin_users enable row level security;

grant select on public.products to anon, authenticated;
grant insert, update, delete on public.products to authenticated;
grant select on public.admin_users to authenticated;

drop policy if exists "Published products are public" on public.products;
drop policy if exists "Products are public" on public.products;
create policy "Products are public"
  on public.products for select
  using (true);

drop policy if exists "Admins can insert products" on public.products;
create policy "Admins can insert products"
  on public.products for insert to authenticated
  with check ((select public.is_zoenaturals_admin()));

drop policy if exists "Admins can update products" on public.products;
create policy "Admins can update products"
  on public.products for update to authenticated
  using ((select public.is_zoenaturals_admin()))
  with check ((select public.is_zoenaturals_admin()));

drop policy if exists "Admins can delete products" on public.products;
create policy "Admins can delete products"
  on public.products for delete to authenticated
  using ((select public.is_zoenaturals_admin()));

drop policy if exists "Admins can read own membership" on public.admin_users;
create policy "Admins can read own membership"
  on public.admin_users for select to authenticated
  using (user_id = (select auth.uid()));

create or replace function public.set_product_updated_at()
returns trigger
language plpgsql
set search_path = ''
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists products_updated_at on public.products;
create trigger products_updated_at
  before update on public.products
  for each row execute function public.set_product_updated_at();

create table if not exists public.orders (
  reference text primary key,
  customer jsonb not null,
  amount_kobo bigint not null check (amount_kobo > 0),
  payment_method text not null check (payment_method in ('paystack', 'pod')),
  status text not null check (status in ('pending', 'paid', 'failed', 'pod_pending', 'packed', 'shipped', 'delivered')),
  authorization_url text,
  expires_at timestamptz not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  paid_at timestamptz
);

create table if not exists public.order_items (
  id bigint generated by default as identity primary key,
  reference text not null references public.orders(reference) on delete cascade,
  product_id uuid not null,
  product_name text not null,
  variant_id text,
  qty integer not null check (qty > 0),
  unit_price_kobo bigint not null check (unit_price_kobo >= 0)
);

alter table public.order_items add column if not exists id bigint generated by default as identity;
alter table public.order_items add column if not exists variant_id text;
alter table public.order_items drop constraint if exists order_items_pkey;
alter table public.order_items add constraint order_items_pkey primary key (id);
alter table public.orders drop constraint if exists orders_status_check;
alter table public.orders add constraint orders_status_check
  check (status in ('pending', 'paid', 'failed', 'pod_pending', 'packed', 'shipped', 'delivered'));

create index if not exists order_items_product_id_idx
  on public.order_items (product_id);

alter table public.orders enable row level security;
alter table public.order_items enable row level security;

revoke all on public.orders, public.order_items from anon, authenticated;
grant all on public.orders, public.order_items to service_role;

create or replace function public.create_zoenaturals_order(
  p_reference text,
  p_customer jsonb,
  p_items jsonb,
  p_payment_method text
)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_item jsonb;
  v_product record;
  v_variant jsonb;
  v_variant_id text;
  v_unit_price numeric(12, 2);
  v_available integer;
  v_qty integer;
  v_reserved integer;
  v_total_kobo bigint := 0;
  v_expires_at timestamptz;
begin
  if p_payment_method not in ('paystack', 'pod') then
    raise exception 'INVALID_PAYMENT_METHOD';
  end if;
  if jsonb_typeof(p_customer) <> 'object' or jsonb_typeof(p_items) <> 'array' then
    raise exception 'INVALID_ORDER';
  end if;
  if jsonb_array_length(p_items) = 0 then
    raise exception 'INVALID_ORDER';
  end if;

  v_expires_at := case
    when p_payment_method = 'paystack' then now() + interval '30 minutes'
    else now() + interval '30 days'
  end;

  insert into public.orders (
    reference, customer, amount_kobo, payment_method, status, expires_at
  ) values (
    p_reference, p_customer, 1, p_payment_method,
    case when p_payment_method = 'paystack' then 'pending' else 'pod_pending' end,
    v_expires_at
  );

  for v_item in
    select value
    from jsonb_array_elements(p_items)
    order by value->>'productId'
  loop
    v_qty := (v_item->>'qty')::integer;
    v_variant_id := nullif(v_item->>'variantId', '');
    v_variant := null;
    select id, name, price, sale_price, stock, variants
      into v_product
      from public.products
      where id = (v_item->>'productId')::uuid and published = true
      for update;

    if not found then
      raise exception 'PRODUCT_NOT_FOUND';
    end if;

    if jsonb_array_length(v_product.variants) > 0 then
      select value
        into v_variant
        from jsonb_array_elements(v_product.variants) as variants(value)
        where value->>'id' = v_variant_id;
      if v_variant is null then
        raise exception 'VARIANT_NOT_FOUND:%', v_product.name;
      end if;
      v_unit_price := coalesce(
        nullif(coalesce(v_variant->>'salePrice', v_variant->>'sale_price'), '')::numeric,
        v_product.sale_price,
        nullif(v_variant->>'price', '')::numeric,
        v_product.price
      );
      v_available := greatest(0, coalesce((v_variant->>'stock')::integer, 0));
    else
      if v_variant_id is not null then
        raise exception 'VARIANT_NOT_FOUND:%', v_product.name;
      end if;
      v_unit_price := coalesce(v_product.sale_price, v_product.price);
      v_available := v_product.stock;
    end if;

    if p_payment_method = 'paystack' then
      select coalesce(sum(oi.qty), 0)::integer
        into v_reserved
        from public.order_items oi
        join public.orders o on o.reference = oi.reference
        where oi.product_id = v_product.id
          and oi.variant_id is not distinct from v_variant_id
          and o.status = 'pending'
          and o.expires_at > now();

      if v_qty > v_available - v_reserved then
        raise exception 'INSUFFICIENT_STOCK:%:%',
          v_product.name, greatest(0, v_available - v_reserved);
      end if;
    end if;

    v_total_kobo := v_total_kobo + round(v_unit_price * 100)::bigint * v_qty;
    insert into public.order_items (
      reference, product_id, product_name, variant_id, qty, unit_price_kobo
    ) values (
      p_reference, v_product.id, v_product.name, v_variant_id, v_qty,
      round(v_unit_price * 100)::bigint
    );
  end loop;

  if v_total_kobo <= 0 then
    raise exception 'INVALID_ORDER_TOTAL';
  end if;

  update public.orders
    set amount_kobo = v_total_kobo
    where reference = p_reference;

  return jsonb_build_object(
    'reference', p_reference,
    'amount_kobo', v_total_kobo,
    'amount', v_total_kobo / 100.0,
    'status', case when p_payment_method = 'paystack' then 'pending' else 'pod_pending' end
  );
end;
$$;

revoke all on function public.create_zoenaturals_order(text, jsonb, jsonb, text)
  from public, anon, authenticated;
grant execute on function public.create_zoenaturals_order(text, jsonb, jsonb, text)
  to service_role;

create or replace function public.complete_zoenaturals_order(p_reference text)
returns boolean
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_order record;
  v_item record;
  v_stock integer;
begin
  select status, payment_method
    into v_order
    from public.orders
    where reference = p_reference
    for update;

  if not found then
    raise exception 'ORDER_NOT_FOUND';
  end if;
  if v_order.status = 'paid' then
    return true;
  end if;
  if v_order.status <> 'pending' or v_order.payment_method <> 'paystack' then
    raise exception 'ORDER_NOT_PAYABLE';
  end if;

  for v_item in
    select product_id, variant_id, qty
      from public.order_items
      where reference = p_reference
      order by product_id
  loop
    if v_item.variant_id is null then
      select stock into v_stock from public.products
        where id = v_item.product_id for update;
      if not found or v_stock < v_item.qty then
        raise exception 'INSUFFICIENT_STOCK_ON_PAYMENT';
      end if;
      update public.products set stock = stock - v_item.qty,
        sales_count = sales_count + v_item.qty
        where id = v_item.product_id;
    else
      update public.products p
        set variants = (
          select jsonb_agg(
            case when items.variant->>'id' = v_item.variant_id
              then jsonb_set(items.variant, '{stock}',
                to_jsonb(greatest(0, coalesce((items.variant->>'stock')::integer, 0) - v_item.qty)))
              else items.variant
            end
          )
          from jsonb_array_elements(p.variants) as items(variant)
        ),
        sales_count = p.sales_count + v_item.qty
        where p.id = v_item.product_id
          and exists (
            select 1 from jsonb_array_elements(p.variants) as items(variant)
              where items.variant->>'id' = v_item.variant_id
                and coalesce((items.variant->>'stock')::integer, 0) >= v_item.qty
          );
      if not found then
        raise exception 'INSUFFICIENT_STOCK_ON_PAYMENT';
      end if;
    end if;
  end loop;

  update public.orders
    set status = 'paid', paid_at = now(), updated_at = now()
    where reference = p_reference;
  return true;
end;
$$;

revoke all on function public.complete_zoenaturals_order(text)
  from public, anon, authenticated;
grant execute on function public.complete_zoenaturals_order(text)
  to service_role;

-- After creating the admin account in Supabase Auth, grant membership:
-- insert into public.admin_users (user_id)
-- select id from auth.users where email = 'admin@example.com'
-- on conflict do nothing;